import json

# name -> commons file title (as it appears after "File:" on commons, spaces = spaces here, will slugify)
mapping = {
    "Edwin van der Sar": "Edwin van der Sar 2015.jpg",
    "Julio César": "Júlio César FC Internazionale.jpg",
    "Keylor Navas": "Keylor Navas 2018 (cropped).jpg",
    "Jan Oblak": "Jan Oblak 2021.jpg",
    "Alisson Becker": "Alisson Becker Brazil V Morocco 13 June 2026-117 (cropped).jpg",
    "Ederson": "Ederson Moraes (36243872090) (cropped).jpg",
    "Marc-André ter Stegen": "Marc-André ter Stegen (cropped).jpg",
    "Thibaut Courtois": "Thibaut Courtois at the 2018 World Cup (cropped).jpg",
    "Fabien Barthez": "Fabien Barthez.jpg",
    "Fabio Cannavaro": "Fabio Cannavaro 2017.jpg",
    "Franco Baresi": "Franco Baresi 2012.jpg",
    "Vincent Kompany": "Vincent Kompany.jpg",
    "Nemanja Vidić": "Nemanja Vidić (cropped).jpg",
    "Leonardo Bonucci": "Leonardo Bonucci BGR-ITA 2012.jpg",
    "Giorgio Chiellini": "Giorgio Chiellini (edited).jpg",
    "Andrea Barzagli": "Andrea Barzagli (Juventus).jpg",
    "Ashley Cole": "Ashley Cole LA Galaxy (cropped).jpg",
    "Patrice Evra": "Patrice Evra (52472689279) (cropped).jpg",
    "Alphonso Davies": "Alphonso Davies - cropped.jpg",
    "Theo Hernández": "Theo Hernandez France v Senegal 16 June 2026-222 (cropped).jpg",
    "Achraf Hakimi": "Achraf Hakimi vs Niger (cropped).jpg",
    "João Cancelo": "João Cancelo (9).jpg",
    "Jules Koundé": "Jules Koundé (cropped).jpg",
    "William Saliba": "William Saliba France v Senegal 16 June 2026-336.jpg",
    "Trent Alexander-Arnold": "Trent Alexander-Arnold 2018 (cropped).jpg",
    "Kyle Walker": "Kyle Walker.jpg",
    "Gary Neville": "Gary Neville.jpg",
    "Marcel Desailly": "MarcelDesailly.JPG",
    "Laurent Blanc": "Laurent blanc 11 11 2013 reves de Clara.jpg",
    "Marco Verratti": "Marco Verratti 2015 (cropped).jpg",
    "Yaya Touré": "Yaya Touré (cropped).jpg",
    "Michael Essien": "Michael Essien 4636.jpg",
    "Patrick Vieira": "Patrick Vieira.jpg",
    "Claude Makélélé": "Claude Makélélé (53557564951) (cropped).jpg",
    "Michael Ballack": "Michael Ballack 2009 cropped.jpg",
    "Paul Scholes": "Paul Scholes 2017.jpg",
    "Ryan Giggs": "Ryan Giggs in 2008.jpg",
    "Juan Román Riquelme": "Juan Román Riquelme - 2019.jpg",
    "Pablo Aimar": "Pablo Aimar Argentina v Egypt 7 July 2026-080.jpg",
    "Robert Pirès": "Robert Pires1.JPG",
    "Youri Djorkaeff": "Youri Djorkaeff takes a corner (cropped).jpg",
    "Hristo Stoichkov": "Stoichkov in 2016.jpg",
    "Gheorghe Hagi": "Gheorghe Hagi3 cropped.jpg",
    "George Best": "George Best (1976).jpg",
    "Bobby Charlton": "Bobby Charlton Portrait.jpg",
    "Franz Beckenbauer": "Franz Beckenbauer (1975).jpg",
    "Johan Cruyff": "Johan Cruijff (1974).jpg",
    "Bruno Fernandes": "Bruno Fernandes Portugal, 2018.jpg",
    "Martin Ødegaard": "Martin Odegaard Morocco v Norway 7 June 2026-56 (cropped).jpg",
    "Federico Valverde": "Federico Valverde 2021 (cropped).jpg",
    "Aurélien Tchouaméni": "Aurélien Tchouaméni.jpg",
    "Eduardo Camavinga": "Eduardo Camavinga, in Rennes, after his victory in Coupe de France, April 28th, 2019.png",
    "Enzo Fernández": "Enzo Fernández.jpg",
    "Declan Rice": "Declan Rice September 2021.jpg",
    "Ilkay Gündoğan": "Ilkay Gündogan (16391883485).jpg",
    "Frenkie de Jong": "Frenkie de Jong (2019).jpg",
    "Pedri": "Pedri.jpg",
    "Edgar Davids": "Edgar Davids (cropped).jpg",
    "Rodrygo": "Rodrygo 2023 (cropped).jpg",
    "Romelu Lukaku": "Romelu Lukaku 2021.jpg",
    "Edinson Cavani": "Edinson Cavani 2018 (cropped).jpg",
    "Michael Owen": "Michael Owen 072007 cropped.jpg",
    "Olivier Giroud": "Olivier Giroud 2018.jpg",
    "Ronaldo Nazário": "Ronaldo (brazil) (cropped).JPG",
    "Robinho": "Robinho 2012.jpg",
    "Hulk": "Givanildo Vieira de Souza (Hulk).jpg",
    "Alexis Sánchez": "Alexis Sánchez 2017.jpg",
    "Riyad Mahrez": "Riyad Mahrez.jpg",
    "Hakim Ziyech": "Hakim Ziyech 2021.jpg",
    "Pierre-Emerick Aubameyang": "1 Pierre-Emerick Aubameyang (cropped).jpg",
    "Ousmane Dembélé": "Ousmane Dembélé 2018 (cropped).jpg",
    "Marcus Rashford": "Marcus Rashford.jpg",
    "Marco van Basten": "Marco van Basten (ca 2006).jpg",
    "Ruud van Nistelrooy": "Ruud van Nistelrooy 2017.jpg",
    "Dennis Bergkamp": "Dennis Bergkamp 2014.jpg",
    "Diego Costa": "Diego Costa 2012 Rayo Vallecano.jpg",
    "Diego Forlán": "Diego Forlán.jpg",
    "David Villa": "David Villa - 01.jpg",
    "Fernando Morientes": "Fernando Morientes 2010.jpg",
    "Filippo Inzaghi": "Filippo Inzaghi 2011.jpg",
    "Victor Osimhen": "Victor Osimhen (LOSC) (cropped).jpg",
    "Julián Álvarez": "Julián Álvarez (footballer) 2023.jpg",
    "Rafael Leão": "Rafael Leão WC2022.jpg",
    "Khvicha Kvaratskhelia": "Khvicha Kvaratskhelia cropped.jpg",
    "Phil Foden": "Phil Foden 2022.jpeg",
    "Jack Grealish": "Jack Grealish 2021.jpg",
    "Jadon Sancho": "Jadon Sancho 2020.jpg",
    "Raheem Sterling": "Raheem Sterling 2018.jpg",
    "José Mourinho": "José Mourinho (cropped).jpg",
    "Arsène Wenger": "Arsene Wenger JHayes (cropped).jpg",
    "Jürgen Klopp": "Juergen Klopp 2014 (cropped).jpg",
    "Carlo Ancelotti": "Carlo Ancelotti 2016 (cropped).jpg",
    "Alex Ferguson": "Alex Ferguson 02.jpg",
    "Fabio Capello": "Fabio Capello 2018 - 1.jpg",
    "Louis van Gaal": "Louis van Gaal 2014.jpg",
    "Vicente del Bosque": "Vicente del Bosque - Teamchef Spain (02) (cropped).jpg",
    "Marcelo Bielsa": "Marcelo Bielsa OM 2015 Cropped.jpg",
    "Antonio Conte": "Antonio Conte.jpg",
    "Thomas Tuchel": "Thomas Tuchel.jpg",
    "Mauricio Pochettino": "Mauricio Pochettino 2016 (cropped).jpg",
}

print(len(mapping))
with open('image_mapping.json', 'w', encoding='utf-8') as f:
    json.dump(mapping, f, ensure_ascii=False, indent=2)
