  "Edwin van der Sar": "https://commons.wikimedia.org/wiki/Special:FilePath/Edwin_van_der_Sar_2015.jpg",
  "Julio César": "https://commons.wikimedia.org/wiki/Special:FilePath/J%C3%BAlio_C%C3%A9sar_FC_Internazionale.jpg",
  "Keylor Navas": "https://commons.wikimedia.org/wiki/Special:FilePath/Keylor_Navas_2018_(cropped).jpg",
  "Jan Oblak": "https://commons.wikimedia.org/wiki/Special:FilePath/Jan_Oblak_2021.jpg",
  "Alisson Becker": "https://commons.wikimedia.org/wiki/Special:FilePath/Alisson_Becker_Brazil_V_Morocco_13_June_2026-117_(cropped).jpg",
  "Ederson": "https://commons.wikimedia.org/wiki/Special:FilePath/Ederson_Moraes_(36243872090)_(cropped).jpg",
  "Marc-André ter Stegen": "https://commons.wikimedia.org/wiki/Special:FilePath/Marc-Andr%C3%A9_ter_Stegen_(cropped).jpg",
  "Thibaut Courtois": "https://commons.wikimedia.org/wiki/Special:FilePath/Thibaut_Courtois_at_the_2018_World_Cup_(cropped).jpg",
  "Fabien Barthez": "https://commons.wikimedia.org/wiki/Special:FilePath/Fabien_Barthez.jpg",
  "Fabio Cannavaro": "https://commons.wikimedia.org/wiki/Special:FilePath/Fabio_Cannavaro_2017.jpg",
  "Franco Baresi": "https://commons.wikimedia.org/wiki/Special:FilePath/Franco_Baresi_2012.jpg",
  "Vincent Kompany": "https://commons.wikimedia.org/wiki/Special:FilePath/Vincent_Kompany.jpg",
  "Nemanja Vidić": "https://commons.wikimedia.org/wiki/Special:FilePath/Nemanja_Vidi%C4%87_(cropped).jpg",
  "Leonardo Bonucci": "https://commons.wikimedia.org/wiki/Special:FilePath/Leonardo_Bonucci_BGR-ITA_2012.jpg",
  "Giorgio Chiellini": "https://commons.wikimedia.org/wiki/Special:FilePath/Giorgio_Chiellini_(edited).jpg",
  "Andrea Barzagli": "https://commons.wikimedia.org/wiki/Special:FilePath/Andrea_Barzagli_(Juventus).jpg",
  "Ashley Cole": "https://commons.wikimedia.org/wiki/Special:FilePath/Ashley_Cole_LA_Galaxy_(cropped).jpg",
  "Patrice Evra": "https://commons.wikimedia.org/wiki/Special:FilePath/Patrice_Evra_(52472689279)_(cropped).jpg",
  "Alphonso Davies": "https://commons.wikimedia.org/wiki/Special:FilePath/Alphonso_Davies_-_cropped.jpg",
  "Theo Hernández": "https://commons.wikimedia.org/wiki/Special:FilePath/Theo_Hernandez_France_v_Senegal_16_June_2026-222_(cropped).jpg",
  "Achraf Hakimi": "https://commons.wikimedia.org/wiki/Special:FilePath/Achraf_Hakimi_vs_Niger_(cropped).jpg",
  "João Cancelo": "https://commons.wikimedia.org/wiki/Special:FilePath/Jo%C3%A3o_Cancelo_(9).jpg",
  "Jules Koundé": "https://commons.wikimedia.org/wiki/Special:FilePath/Jules_Kound%C3%A9_(cropped).jpg",
  "William Saliba": "https://commons.wikimedia.org/wiki/Special:FilePath/William_Saliba_France_v_Senegal_16_June_2026-336.jpg",
  "Trent Alexander-Arnold": "https://commons.wikimedia.org/wiki/Special:FilePath/Trent_Alexander-Arnold_2018_(cropped).jpg",
  "Kyle Walker": "https://commons.wikimedia.org/wiki/Special:FilePath/Kyle_Walker.jpg",
  "Gary Neville": "https://commons.wikimedia.org/wiki/Special:FilePath/Gary_Neville.jpg",
  "Marcel Desailly": "https://commons.wikimedia.org/wiki/Special:FilePath/MarcelDesailly.JPG",
  "Laurent Blanc": "https://commons.wikimedia.org/wiki/Special:FilePath/Laurent_blanc_11_11_2013_reves_de_Clara.jpg",
  "Marco Verratti": "https://commons.wikimedia.org/wiki/Special:FilePath/Marco_Verratti_2015_(cropped).jpg",
  "Yaya Touré": "https://commons.wikimedia.org/wiki/Special:FilePath/Yaya_Tour%C3%A9_(cropped).jpg",
  "Michael Essien": "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_Essien_4636.jpg",
  "Patrick Vieira": "https://commons.wikimedia.org/wiki/Special:FilePath/Patrick_Vieira.jpg",
  "Claude Makélélé": "https://commons.wikimedia.org/wiki/Special:FilePath/Claude_Mak%C3%A9l%C3%A9l%C3%A9_(53557564951)_(cropped).jpg",
  "Michael Ballack": "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_Ballack_2009_cropped.jpg",
  "Paul Scholes": "https://commons.wikimedia.org/wiki/Special:FilePath/Paul_Scholes_2017.jpg",
  "Ryan Giggs": "https://commons.wikimedia.org/wiki/Special:FilePath/Ryan_Giggs_in_2008.jpg",
  "Juan Román Riquelme": "https://commons.wikimedia.org/wiki/Special:FilePath/Juan_Rom%C3%A1n_Riquelme_-_2019.jpg",
  "Pablo Aimar": "https://commons.wikimedia.org/wiki/Special:FilePath/Pablo_Aimar_Argentina_v_Egypt_7_July_2026-080.jpg",
  "Robert Pirès": "https://commons.wikimedia.org/wiki/Special:FilePath/Robert_Pires1.JPG",
  "Youri Djorkaeff": "https://commons.wikimedia.org/wiki/Special:FilePath/Youri_Djorkaeff_takes_a_corner_(cropped).jpg",
  "Hristo Stoichkov": "https://commons.wikimedia.org/wiki/Special:FilePath/Stoichkov_in_2016.jpg",
  "Gheorghe Hagi": "https://commons.wikimedia.org/wiki/Special:FilePath/Gheorghe_Hagi3_cropped.jpg",
  "George Best": "https://commons.wikimedia.org/wiki/Special:FilePath/George_Best_(1976).jpg",
  "Bobby Charlton": "https://commons.wikimedia.org/wiki/Special:FilePath/Bobby_Charlton_Portrait.jpg",
  "Franz Beckenbauer": "https://commons.wikimedia.org/wiki/Special:FilePath/Franz_Beckenbauer_(1975).jpg",
  "Johan Cruyff": "https://commons.wikimedia.org/wiki/Special:FilePath/Johan_Cruijff_(1974).jpg",
  "Bruno Fernandes": "https://commons.wikimedia.org/wiki/Special:FilePath/Bruno_Fernandes_Portugal,_2018.jpg",
  "Martin Ødegaard": "https://commons.wikimedia.org/wiki/Special:FilePath/Martin_Odegaard_Morocco_v_Norway_7_June_2026-56_(cropped).jpg",
  "Federico Valverde": "https://commons.wikimedia.org/wiki/Special:FilePath/Federico_Valverde_2021_(cropped).jpg",
  "Aurélien Tchouaméni": "https://commons.wikimedia.org/wiki/Special:FilePath/Aur%C3%A9lien_Tchouam%C3%A9ni.jpg",
  "Eduardo Camavinga": "https://commons.wikimedia.org/wiki/Special:FilePath/Eduardo_Camavinga,_in_Rennes,_after_his_victory_in_Coupe_de_France,_April_28th,_2019.png",
  "Enzo Fernández": "https://commons.wikimedia.org/wiki/Special:FilePath/Enzo_Fern%C3%A1ndez.jpg",
  "Declan Rice": "https://commons.wikimedia.org/wiki/Special:FilePath/Declan_Rice_September_2021.jpg",
  "Ilkay Gündoğan": "https://commons.wikimedia.org/wiki/Special:FilePath/Ilkay_G%C3%BCndogan_(16391883485).jpg",
  "Frenkie de Jong": "https://commons.wikimedia.org/wiki/Special:FilePath/Frenkie_de_Jong_(2019).jpg",
  "Pedri": "https://commons.wikimedia.org/wiki/Special:FilePath/Pedri.jpg",
  "Edgar Davids": "https://commons.wikimedia.org/wiki/Special:FilePath/Edgar_Davids_(cropped).jpg",
  "Rodrygo": "https://commons.wikimedia.org/wiki/Special:FilePath/Rodrygo_2023_(cropped).jpg",
  "Romelu Lukaku": "https://commons.wikimedia.org/wiki/Special:FilePath/Romelu_Lukaku_2021.jpg",
  "Edinson Cavani": "https://commons.wikimedia.org/wiki/Special:FilePath/Edinson_Cavani_2018_(cropped).jpg",
  "Michael Owen": "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_Owen_072007_cropped.jpg",
  "Olivier Giroud": "https://commons.wikimedia.org/wiki/Special:FilePath/Olivier_Giroud_2018.jpg",
  "Ronaldo Nazário": "https://commons.wikimedia.org/wiki/Special:FilePath/Ronaldo_(brazil)_(cropped).JPG",
  "Robinho": "https://commons.wikimedia.org/wiki/Special:FilePath/Robinho_2012.jpg",
  "Hulk": "https://commons.wikimedia.org/wiki/Special:FilePath/Givanildo_Vieira_de_Souza_(Hulk).jpg",
  "Alexis Sánchez": "https://commons.wikimedia.org/wiki/Special:FilePath/Alexis_S%C3%A1nchez_2017.jpg",
  "Riyad Mahrez": "https://commons.wikimedia.org/wiki/Special:FilePath/Riyad_Mahrez.jpg",
  "Hakim Ziyech": "https://commons.wikimedia.org/wiki/Special:FilePath/Hakim_Ziyech_2021.jpg",
  "Pierre-Emerick Aubameyang": "https://commons.wikimedia.org/wiki/Special:FilePath/1_Pierre-Emerick_Aubameyang_(cropped).jpg",
  "Ousmane Dembélé": "https://commons.wikimedia.org/wiki/Special:FilePath/Ousmane_Demb%C3%A9l%C3%A9_2018_(cropped).jpg",
  "Marcus Rashford": "https://commons.wikimedia.org/wiki/Special:FilePath/Marcus_Rashford.jpg",
  "Marco van Basten": "https://commons.wikimedia.org/wiki/Special:FilePath/Marco_van_Basten_(ca_2006).jpg",
  "Ruud van Nistelrooy": "https://commons.wikimedia.org/wiki/Special:FilePath/Ruud_van_Nistelrooy_2017.jpg",
  "Dennis Bergkamp": "https://commons.wikimedia.org/wiki/Special:FilePath/Dennis_Bergkamp_2014.jpg",
  "Diego Costa": "https://commons.wikimedia.org/wiki/Special:FilePath/Diego_Costa_2012_Rayo_Vallecano.jpg",
  "Diego Forlán": "https://commons.wikimedia.org/wiki/Special:FilePath/Diego_Forl%C3%A1n.jpg",
  "David Villa": "https://commons.wikimedia.org/wiki/Special:FilePath/David_Villa_-_01.jpg",
  "Fernando Morientes": "https://commons.wikimedia.org/wiki/Special:FilePath/Fernando_Morientes_2010.jpg",
  "Filippo Inzaghi": "https://commons.wikimedia.org/wiki/Special:FilePath/Filippo_Inzaghi_2011.jpg",
  "Victor Osimhen": "https://commons.wikimedia.org/wiki/Special:FilePath/Victor_Osimhen_(LOSC)_(cropped).jpg",
  "Julián Álvarez": "https://commons.wikimedia.org/wiki/Special:FilePath/Juli%C3%A1n_%C3%81lvarez_(footballer)_2023.jpg",
  "Rafael Leão": "https://commons.wikimedia.org/wiki/Special:FilePath/Rafael_Le%C3%A3o_WC2022.jpg",
  "Khvicha Kvaratskhelia": "https://commons.wikimedia.org/wiki/Special:FilePath/Khvicha_Kvaratskhelia_cropped.jpg",
  "Phil Foden": "https://commons.wikimedia.org/wiki/Special:FilePath/Phil_Foden_2022.jpeg",
  "Jack Grealish": "https://commons.wikimedia.org/wiki/Special:FilePath/Jack_Grealish_2021.jpg",
  "Jadon Sancho": "https://commons.wikimedia.org/wiki/Special:FilePath/Jadon_Sancho_2020.jpg",
  "Raheem Sterling": "https://commons.wikimedia.org/wiki/Special:FilePath/Raheem_Sterling_2018.jpg",
  "José Mourinho": "https://commons.wikimedia.org/wiki/Special:FilePath/Jos%C3%A9_Mourinho_(cropped).jpg",
  "Arsène Wenger": "https://commons.wikimedia.org/wiki/Special:FilePath/Arsene_Wenger_JHayes_(cropped).jpg",
  "Jürgen Klopp": "https://commons.wikimedia.org/wiki/Special:FilePath/Juergen_Klopp_2014_(cropped).jpg",
  "Carlo Ancelotti": "https://commons.wikimedia.org/wiki/Special:FilePath/Carlo_Ancelotti_2016_(cropped).jpg",
  "Alex Ferguson": "https://commons.wikimedia.org/wiki/Special:FilePath/Alex_Ferguson_02.jpg",
  "Fabio Capello": "https://commons.wikimedia.org/wiki/Special:FilePath/Fabio_Capello_2018_-_1.jpg",
  "Louis van Gaal": "https://commons.wikimedia.org/wiki/Special:FilePath/Louis_van_Gaal_2014.jpg",
  "Vicente del Bosque": "https://commons.wikimedia.org/wiki/Special:FilePath/Vicente_del_Bosque_-_Teamchef_Spain_(02)_(cropped).jpg",
  "Marcelo Bielsa": "https://commons.wikimedia.org/wiki/Special:FilePath/Marcelo_Bielsa_OM_2015_Cropped.jpg",
  "Antonio Conte": "https://commons.wikimedia.org/wiki/Special:FilePath/Antonio_Conte.jpg",
  "Thomas Tuchel": "https://commons.wikimedia.org/wiki/Special:FilePath/Thomas_Tuchel.jpg",
  "Mauricio Pochettino": "https://commons.wikimedia.org/wiki/Special:FilePath/Mauricio_Pochettino_2016_(cropped).jpg",
  "Peter Schmeichel": "https://commons.wikimedia.org/wiki/Special:FilePath/Peter_Schmeichel_2012-01-25_001.jpg",
